### PR TITLE
Clean the installation instruction

### PR DESCRIPTION
**Pull request by xiaoruiDong**
[HOLD MERGING] waiting for the trial by Kevin.

I saw your modification in pyrms, where you removed `PyCall` related things. So we don't need to worry about PyCall anymore?

I created a new wiki page about the RMS installation. I personally followed this guide to help people install RMS. The original instruction in README is very confusing at this moment, so I just removed it. Please let me know your thoughts and any suggestions about the wiki page. Thanks.

### CODE REVIEW

**Comment by mjohnson541** [comment]
So installing pyjulia in the appropriate environment actually automatically configures PyCall properly. 

You actually no longer need the full DifferentialEquations you can get by with just Sundials (which is a dependency) currently if you're only using CVODE_BDF.

**Comment by mjohnson541** [comment]
Also technically the pycall configuration only needs done if you have a local source rmg installation. Otherwise julia should just install the dependencies automatically in Julia's python.

**Comment by xiaoruiDong** [comment]
Thanks for the advices.

> You actually no longer need the full DifferentialEquations you can get by with just Sundials (which is a dependency) currently if you're only using CVODE_BDF.

I am assuming DifferentialEquations provide more solvers, is that correct? I can

> Also the pycall configuration only needs done if you have a local source rmg installation. Otherwise julia should just install the dependencies automatically in Julia's python.

One of the problem, Kevin and I found yesterday is that without a pre-existing rmg_env, PyCall may not download the correct version of a package. For example, it will download an earlier version of RDKit and raise an error that the RDKit downloaded does not support python 3.7. Not sure why.

**Comment by mjohnson541** [comment]
I'm pretty sure the python package install is breaking because we're not drawing from the right conda channels anymore.

**Comment by xiaoruiDong** [comment]
> I'm pretty sure the python package install is breaking because we're not drawing from the right conda channels anymore.
I agree, but is there a way to assign the channels? I am curious about which environment setting it is actually followed.

**Comment by mjohnson541** [comment]
pyimport_conda takes it as a third input

**Comment by mjohnson541** [comment]
test comment

**Pull request closed without merging**
