### PR TITLE
Fix Compatibility with rmgpy

### PR DESCRIPTION
**Pull request by mjohnson541**

### CODE REVIEW

**Comment by mjohnson541** [comment]
Fundamentally, the issue with tests seems to be that some bug probably in a sciml package or ReverseDiff.jl is causing adjoint sensitivity analysis to give very wrong answers...I think that is best solved by loosening package restrictions and moving from the DiffEq version of packages to the sciml versions. 

Since this issue doesn't affect RMG edge analysis usage I think we can add this fix now and solve the adjoint sensitivities issue in a new PR. I will remove the debugging commits.

**Comment by mjohnson541** [comment]
Testing compatibility with RMG is done in this PR:  https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2543

**Review by hwpang — COMMENTED** [review]
This seems fine. But why does it fail CI for RMS?

**Review by hwpang — APPROVED** [review]

**Comment by hwpang** [comment]
LGTM. CI and documentation failed due to unrelated reasons and should be fixed in the future.

**Pull request merged**
