### PR TITLE
Fixing dependency conflicts

### PR DESCRIPTION
**Pull request by hwpang**
Switching to `rmgmolecule` instead of `rmg`, as RMS only depends on a small part of RMG functionality covered by `rmgmolecule`.

### CODE REVIEW

**Comment by hwpang** [comment]
It seems that using pydot from conda-forge solves the dependency conflict problem. Switching from rmg to rmgmolecule was not actually necessarily.

**Comment by hwpang** [comment]
I found that adding conda-forge channel and switching to rmgmolecule fix the package conflict problem, but the test failed with matplotlib not found error. I added matplotlib as a requirement.

**Comment by hwpang** [comment]
I changed to use the newly built `rmgmolecule` on my conda channel, which contains the recent changes to add settings to molecule.

**Comment by hwpang** [comment]
There was a bug in the rmgmolecule code. I updated the rmgmolecule code and build the conda package again. I will restart the CI.

**Comment by hwpang** [comment]
The CI passed but the documentation build failed because `molecule.family` tries to import `molecule.constraints`, which doesn't exist. I copied `rmgpy.constraints` over to a personal branch and updated the conda build. I will re-start the documentation build.

**Comment by hwpang** [comment]
I added the missing files to molecule and rebuilt. I will restart the test.

**Comment by hwpang** [comment]
Restart documentation build with new rmgmolecule build

**Comment by hwpang** [comment]
I rebased. Testing with new molecule build.

**Comment by hwpang** [comment]
New push cleans up the commit history

**Review by mjohnson541 — APPROVED** [review]
Looks good

**Pull request merged**
