### PR TITLE
Enabling four party reactions

### PR DESCRIPTION
**Pull request by hwpang**
Expanding the code to handle four party reactions encountered during analyzing the n-heptane combustion model by Curren et al.

### CODE REVIEW

**Comment by hwpang** [comment]
@xiaoruiDong This is the four party branch I mentioned the other day. If you need a version that works for the mechanism that contains 5 party elementary reactions, you may want to start from here.

**Comment by hwpang** [comment]
New push enable `addreactionratecontributionsforwardreverse` for four party reactions

**Review by mjohnson541 — COMMENTED** [review]
I think this looks good. Is this ready to merge?

**Comment by hwpang** [comment]
@mjohnson541 Yes this is ready to merge.

**Pull request merged**
